# Site settings
title: Vinst Blog
SEOTitle: Vinstweb | Vinst Blog
header-img: img/home-bg.jpg
email: vinstweb@gmail.com
description: "前端工程师个人博客 | 分享前端、日常、心情的地方 | 这里是vinst的个人博客。"
keyword: "vinstweb, vin, github, WS, Vinst的博客, Vinst Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端"
url: "https://www.vinstweb.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     websetter
zhihu_username:     hansmwang
github_username:    vinstweb
# twitter_username:   vinstweb
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: vinstweb

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]
ba_track_id: '23c88c26b058eb6b784b020dbb0a09b7'

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "逆水行舟，不进则退。"
sidebar-avatar: /img/avatar-vin.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    title: "NCZOnline",
    href: "https://www.nczonline.net/"
  },
  {
    title: "Coderops",
    href: "https://tympanus.net/codrops/"
  },
  {
    title: "Meyerweb",
    href: "https://meyerweb.com/"
  },
  {
    title: "QuirksBlog",
    href: "https://www.quirksmode.org/blog/"
  },
  {
    title: "Paul Irish",
    href: "https://www.paulirish.com/"
  },
  {
    title: "Addy Osmani",
    href: "https://addyosmani.com/blog/"
  }
]
